name: Windows xScanner CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout xScanner
      uses: actions/checkout@v4
      with:
          submodules: 'true'
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Download wxWidgets
      run:
        git clone --depth=1 --shallow-submodules --recurse-submodules -b xlights_2026.04 https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\

    - name: Build wxWidgets
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"

    - name: Build xScanner
      working-directory: xScanner
      run: msbuild /m:10 xScanner.sln /p:Configuration="Release" -p:Platform="x64"

    - name: Upload xScanner Exe
      uses: actions/upload-artifact@v4
      with:
        name: xScanner_Exe
        path: 'xScanner\x64\Release\xScanner.exe'
